tryber/sd-010-a-project-frontend-online-store

- package-lock.json
- src/App.js
> [Group 10] Req 1 - starting project

- src/App.js
> feat: Name implementation

- src/App.js
>  [Group 10] Req 3 - Name implementation

- src/App.js
- src/components/SearchBar.jsx
Implementar uma barra de busca com mensagem.
> Group 22 - feat: requirement 02

- package-lock.json
- src/App.js
- src/pages/Home.jsx
- src/services/api.js
> Main group 14 req 02

- package-lock.json
- src/App.js
- src/services/api.js
> Requisito 1 - pairPrograming

- src/App.js
- src/components/Shopping-cart-button.js
- src/pages/ShoppingCartPage.jsx
- src/pages/home.js
Alterações nos arquivos App.js, e home.js;
Criação do arquivo ShoppingCartPage e componente ShoppingCartButton
> [Grupo 25] feat: req3 > shopppingCartPage

- src/App.js
- src/components/Home.js
Adicionando componente Home e renderizando no App.
> [Grupo-20] Main group 20 req2

- src/components/Categories.js
- src/pages/Home.js
> [Main group 19] MuriloGon & Roberto - requirement 04 - Liste as categorias de produtos disponíveis via API na página principal

- src/App.js
- src/services/api.js
feat: function getCategories();
feat: function getProductsFromCategoryAndQuery();
> [Group 10] Req 1 - Done

- src/App.js
- src/components/Home.jsx
> feat: req-2

- src/components/Button.jsx
- src/components/Item.jsx
- src/components/ListItems.jsx
- src/components/SearchBar.jsx
- src/pages/Home.jsx
- src/services/api.js
Adiciona requisito 5
refatora as funções de busca na api
Cria componentes ListItems, Item
> Main group 21 req5

- src/App.js
- src/components/CartButton.jsx
- src/pages/Cart.jsx
- src/pages/Home.jsx
> [Grupo 4] Requisito 3 ✔️  

- src/components/Categories.jsx
- src/components/SearchBar.jsx
Adicionado barra de categorias ao lado.
> Grupo 22 - Requirement 04

- src/pages/Home/NotFound.js
- src/pages/Home/components/CardProduct.js
- src/pages/Home/components/Category.js
- src/pages/Home/index.js
- src/services/api.js
Ao selecionar uma categoria, mostra somente os produtos referentes a ela.
Ao clicar em uma categoria disponível, são exibidos em tela os produtos da categoria escolhida.
Quando uma categoria é selecionada, os produtos, no estado do componente `Home`, são atualizados com o _endpoint_ oferecido na documentação do projeto.
> [GRUPO 5] Ao selecionar uma categoria, mostra somente os produtos referentes a ela

- src/components/Categories.js
- src/components/Product.js
- src/components/ProductList.js
- src/components/SearchBar.js
- src/index.js
- src/pages/Home.css
- src/pages/Home.js
> [Main Group 19] - Murilo Gonçaves - Requirement 05 -  Liste os produtos buscados por termos, com os dados resumidos, associados a esses termos

- src/App.js
- src/components/Home.jsx
- src/components/ProductCard.jsx
- src/pages/ProductDetail.jsx
feat: implemented <Link> on ProductCard.jsx to ProductDetails.jsx
> [Group 10] - Feat: requirement 7

- src/components/Categories.js
- src/pages/Home.js
- src/services/api.js
refactor requirement04 - add component categories
> fix: requeriment04

- src/App.js
- src/Components/Details.jsx
> [Group 24] [Req 9]

- src/App.js
- src/Pages/ShoppingCart.jsx
> [Group 24] [Req 10]

- src/components/Evaluation.jsx
- src/pages/ProductDetails.jsx
Está passando no teste e no lint, porém acredito que haja algum erro no teste ou então terá um requisito bônus para terminar o processo de avaliação. Devo refatorar ele no futuro para ser mais funcional
> Group-17-Req11

- .gitignore
- src/App.css
- src/components/comment/ProductEvaluationForm.js
- src/components/comment/RatingStar.js
- src/components/comment/StarIcon.js
> [Group 1] Requisito 11

- src/components/CardItem.js
- src/components/Loading.js
- src/components/Routers.js
- src/pages/ProductDetail.js
- src/services/api.js
- src/services/api2.js
Estava dando problema com o mock dos testes.
Foi necessário transferir a função 'getProductById' que estava no arquivo api.js para outro arquivo.
Acabei, portanto, tendo que  criar este arquivo nomeado de api2.js
> [Group 02] - fix: Requirement07

- src/components/Evaluation.jsx
- src/components/ProductCard.jsx
- src/pages/ProductDetails.jsx
Req 15 mexeu com ProductDetails e ProductCard, apenas adição de código
> Group-17-Req15

- src/App.js
- src/components/Home.jsx
- src/components/ProductCard.jsx
- src/pages/Cart.jsx
feat: implements a method and a state to App component, to handle the addition of products to cart.
> [Group 10] Req 8 - Incompleted Requirement

- src/components/Header.js
- src/components/Home.js
- src/components/ProductList.js
Levando o dia para arrumar um click
> [Grupo 20] req5

- src/components/Header.js
- src/components/ListCategories.js
- Requisito 6:
* Modificamos a função fetchProducts para executar a pesquisa em conjunto com as categorias;
* E passamos essa função como props no componente ListCategories, para buscar o id da categoria;
> [Grupo 20] [Requisito 6]

- src/App.js
- src/components/CategoriesList.jsx
- src/components/Home.jsx
- src/pages/Cart.jsx
feat: implements the Cart List functions to show just one item per ID and its quantity.
> [Group 10] Req 8 - show on Cart just one title per item and its quantity.

- package-lock.json
- package.json
- src/components/Button/index.jsx
- src/components/ListProducts/index.jsx
- src/components/Product/index.jsx
- src/components/Rating/index.jsx
- src/components/Rating/styles.css
- src/pages/Home/index.jsx
- src/pages/ProductDetails/index.jsx
Adicionei a lib react icons, para criar o componente Rating. Alterei alguns nomes de variáveis para deixar o código mais legível e desenvolvi o requisito 11.
> feat: requisito 11 - adicionando campo de avaliacao

- src/App.js
- src/pages/Cart.jsx
- src/pages/ProductDetail.jsx
Implements an method to add and remove cart items;
> [Group 10] - Feat: Requirement 10;

- src/components/product_details.js
Pendente: implementar função handleChange para armazenar e ler informações do LocalStorage
> Main Group 18 - requirement 11 (in process)

- src/components/ProductDetails.jsx
- src/components/SearchBar.jsx
Adicionado funcionalidade de adicionar produto ao carrinho a partir da tela de detalhes
> [GROUP 22] Feat: Requisito 09

- src/App.js
- src/Components/Categories.jsx
- src/Components/Details.jsx
- src/Components/ListagemProdutos.jsx
- src/Components/ProductCard.jsx
- src/Pages/Checkout.jsx
- src/Pages/ShoppingCart.jsx
> [Group 24] [Req 12]

- src/components/ProductDetails.jsx
- src/components/SearchBar.jsx
> [GROUP 22 ] feat-requisito-11

- package-lock.json
- src/App.js
- src/components/Form.jsx
- src/components/Home.jsx
- src/components/formComponents/Address.jsx
- src/components/formComponents/Cep.jsx
- src/components/formComponents/Cpf.jsx
- src/components/formComponents/Email.jsx
- src/components/formComponents/FullName.jsx
- src/components/formComponents/Phone.jsx
- src/pages/Cart.jsx
- src/pages/Checkout.jsx
> [Group 12] - Feat: requirement 12 completed

- src/Routes.js
- src/components/ListProducts/index.jsx
- src/components/Product/index.jsx
- src/pages/Home/index.jsx
- src/pages/ProductDetails/index.jsx
Deu algum erro com o nome da função, mas ta tudo certo agora.
>  [ Grupo 21 ] Fix: requisitos 8 e 9 

- src/App.js
- src/components/Header.js
- src/components/ProductDetails.js
- src/components/ProductList.js
Requisito 7:
Adicionando rota para renderização dos detalhes do produto através do componente ProductDetails.
Ainda não está passando no teste!!
> [Grupo 20] Requisito 7

- .gitignore
- .vscode/settings.json
- package-lock.json
- src/App.css
- src/components/AddButton.js
- src/components/Header.js
- src/components/Home.js
- src/components/ListCategories.js
- src/components/ProductList.js
- src/components/ShopCart.js
- src/components/ShopCartButton.js
- src/services/localStorage.js
2/3 do requisito 8, não fazer o merge pf
> [ Groupo 20 ] Requisito 8 **NÃO MERGEAR**

- src/components/AddButton.js
- src/components/DetailsAddButton.js
- src/components/ProductDetails.js
- src/components/ShopCart.js
- src/components/ShopCartButton.js
Requisito 9:
Adicionamos o AddButton ao ProductDetails e passamos como props os dados.
Ainda não está passando no test.
> [Grupo 20 ] Requisito 9 **NÃO MERGIAR**

- src/components/DetailsAddButton.js
- src/components/ProductDetails.js
- src/components/ShopCart.js
- src/components/ShopCartItem.js
Pessoal, consegui resolver o requisito 9, mas quando dei esse pull, ficou uns erros no lint, então, o evaluator não vai rodar, mas farei outro commit aqui, com a fix e vou explicar as alterações feitas.
> [Grupo 20] [Requisito 9 - Conseguimos !!!] 

- src/components/ProductDetails.js
- src/components/ProductEvaluation.js
Requisito 11, feio mas feito e funcional, irei deixar mais apresentavel em breve
> [ Grupo 20 ] Requisito 11

- src/App.js
- src/__tests__/requirement12.test.js
- src/pages/CartContent.jsx
- src/pages/Checkout.jsx
Criação da pagina de finalização da compra. Adiciona um botão na pagina do carrinho de compras que redireciona para essa nova pagina.
> Grupo 16 - Requisito 12
